const LAYOUT_KEY = "link-extractor-admin-layout-v1";
let layoutEditing = false, layoutSnapshot = null;
/* v1.17.2：补登记 "members"（v1.14.0 新增的成员署名模块当时漏了它）。
   不登记的后果：老用户浏览器里的旧布局、或点「恢复默认」时，applyLayout 只
   append 清单内模块，members 从未被移动 → 被挤到看板最顶部（视觉错位）。 */
const defaultLayout = ["status","alerts","metrics","performance","insights","members","devices","analysis","pool"];
export function layoutModules() { return [...document.querySelectorAll("#dashboardGrid > .dashboard-module")]; }
export function readLayout() { try { return JSON.parse(localStorage.getItem(LAYOUT_KEY) || "null"); } catch (_) { return null; } }
export function saveLayout() { const data = layoutModules().map(m => ({id:m.dataset.module, size:m.classList.contains("half") ? "half" : m.classList.contains("third") ? "third" : "full", hidden:m.classList.contains("module-hidden")})); localStorage.setItem(LAYOUT_KEY, JSON.stringify(data)); }
export function applyLayout(data) { const grid=document.getElementById("dashboardGrid"); const map=Object.fromEntries(layoutModules().map(m=>[m.dataset.module,m])); (data || defaultLayout.map(id=>({id,size:"full",hidden:false}))).forEach(item => { const m=map[item.id]; if (!m) return; grid.appendChild(m); m.classList.remove("full","half","third","module-hidden"); m.classList.add(item.size || "full"); if (item.hidden) m.classList.add("module-hidden"); m.style.height=item.height || ""; }); }
export function addModuleActions() { layoutModules().forEach(m => { const a=m.querySelector(".module-actions"); if (a && !a.children.length) a.innerHTML='<button class="module-action" data-action="size">宽度</button><button class="module-action" data-action="auto">自适应</button><button class="module-action" data-action="hide">隐藏</button>'; if (!m.querySelector(".resize-hint")) { const hint=document.createElement("span"); hint.className="resize-hint"; hint.textContent="↘ 拖动调整高度"; m.appendChild(hint); } m.draggable=false; }); }
export function setEdit(on) { layoutEditing=on; document.getElementById("content").classList.toggle("editing",on); document.getElementById("editLayoutBtn").classList.toggle("hidden",on); document.getElementById("resetLayoutBtn").classList.toggle("hidden",!on); document.getElementById("saveLayoutBtn").classList.toggle("hidden",!on); document.getElementById("cancelLayoutBtn").classList.toggle("hidden",!on); document.getElementById("layoutState").textContent=on ? "编辑模式 · 拖动排序 / 尺寸 / 隐藏" : "查看模式 · 布局自动保存"; layoutModules().forEach(m=>m.draggable=on); setSubEditing(on); }

export function subModules() { return [...document.querySelectorAll(".insight-grid > .card, .bottom-grid > .card")]; }
export function initSubModules() { subModules().forEach((m,i) => { if (!m.dataset.submodule) m.dataset.submodule = (m.querySelector("h2")?.textContent || "组件").trim() + "-" + i; if (!m.querySelector(".submodule-head")) { const h=document.createElement("div"); h.className="submodule-head"; h.innerHTML='<span class="sub-drag">⠿</span><b>'+(m.querySelector("h2")?.textContent || "小组件")+'</b><span class="sub-actions"><button class="module-action" data-sub-action="hide">隐藏</button><button class="module-action" data-sub-action="auto">自适应</button></span>'; m.prepend(h); const r=document.createElement("span"); r.className="submodule-resize"; r.textContent="↘ 拖动调整"; m.appendChild(r); } }); }
export function setSubEditing(on) { subModules().forEach(m => m.draggable=on); }

export function initLayoutEditor() { addModuleActions(); initSubModules(); applyLayout(readLayout()); const grid=document.getElementById("dashboardGrid");
  grid.addEventListener("pointerdown", e => { if(!layoutEditing || !e.target.classList.contains("resize-hint")) return; const m=e.target.closest(".dashboard-module"), startY=e.clientY, startH=m.getBoundingClientRect().height; m.setPointerCapture(e.pointerId); const move=ev => { const h=Math.max(120, Math.round(startH + ev.clientY-startY)); m.style.height=h+"px"; }; const up=()=>{ m.releasePointerCapture(e.pointerId); m.removeEventListener("pointermove",move); m.removeEventListener("pointerup",up); }; m.addEventListener("pointermove",move); m.addEventListener("pointerup",up); });
  grid.addEventListener("dragstart",e=>{ if(!layoutEditing || !e.target.classList.contains("dashboard-module")) return; e.target.classList.add("dragging"); e.dataTransfer.effectAllowed="move"; }); grid.addEventListener("dragend",e=>e.target.classList.remove("dragging")); grid.addEventListener("dragover",e=>{ if(!layoutEditing) return; e.preventDefault(); const drag=grid.querySelector(".dragging"), over=e.target.closest(".dashboard-module"); if(drag && over && drag!==over){ const r=over.getBoundingClientRect(); grid.insertBefore(drag, e.clientY < r.top+r.height/2 ? over : over.nextSibling); }}); grid.addEventListener("click",e=>{ const btn=e.target.closest(".module-action"); if(!btn) return; const m=btn.closest(".dashboard-module"); if(btn.dataset.action==="hide") m.classList.add("module-hidden"); else if(btn.dataset.action==="auto") { m.style.height=""; m.style.minHeight=""; } else { const sizes=["full","half","third"]; const next=sizes[(sizes.indexOf(m.classList.contains("half")?"half":m.classList.contains("third")?"third":"full")+1)%3]; m.classList.remove("full","half","third"); m.classList.add(next); }}); grid.addEventListener("click", e => { const btn=e.target.closest("[data-sub-action]"); if(!btn || !layoutEditing) return; const m=btn.closest(".insight-grid > .card, .bottom-grid > .card"); if(btn.dataset.subAction==="hide") m.classList.add("module-hidden"); else m.style.height=""; });
  document.querySelectorAll(".insight-grid, .bottom-grid").forEach(group => group.addEventListener("dragover", e => { if(!layoutEditing) return; const drag=group.querySelector(".dragging-sub"), over=e.target.closest(":scope > .card"); if(!drag || !over || drag===over) return; e.preventDefault(); const r=over.getBoundingClientRect(); group.insertBefore(drag,e.clientY<r.top+r.height/2?over:over.nextSibling); }));
  subModules().forEach(m=>m.addEventListener("dragstart", e=>{ if(!layoutEditing) return; m.classList.add("dragging-sub"); })); subModules().forEach(m=>m.addEventListener("dragend", e=>m.classList.remove("dragging-sub")));
  document.getElementById("editLayoutBtn").onclick=()=>{ layoutSnapshot=JSON.stringify(readLayout()); setEdit(true); }; document.getElementById("cancelLayoutBtn").onclick=()=>{ applyLayout(JSON.parse(layoutSnapshot)||null); setEdit(false); }; document.getElementById("saveLayoutBtn").onclick=()=>{ saveLayout(); setEdit(false); }; document.getElementById("resetLayoutBtn").onclick=()=>{ applyLayout(null); }; }
initLayoutEditor();